#!/usr/bin/env node
/**
 * Interaction coverage report — which clickable elements in charts / dashboards / reports did no
 * E2E test interact with?
 *
 *   npm run e2e:interactions:record   # full suite with E2E_RECORD_INTERACTIONS=on
 *   npm run e2e:interactions:report   # → e2e/coverage/INTERACTIONS.md
 *
 * Inputs: test-results/interactions/*.jsonl (support/interactions.ts) + the static inventory
 * (interaction-inventory.mjs). A touched testid covers an inventory entry when it equals the
 * entry's value or matches its regex.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { buildInventory, countInventory, ROOT } from './interaction-inventory.mjs';

const INTERACTIONS_DIR = path.join(ROOT, 'test-results/interactions');
const OUT = path.join(ROOT, 'e2e/coverage/INTERACTIONS.md');

function readRuns() {
  if (!existsSync(INTERACTIONS_DIR)) return [];
  const lines = [];
  for (const name of readdirSync(INTERACTIONS_DIR)
    .filter((n) => n.endsWith('.jsonl'))
    .sort()) {
    for (const line of readFileSync(path.join(INTERACTIONS_DIR, name), 'utf8').split('\n')) {
      if (!line.trim()) continue;
      try {
        lines.push(JSON.parse(line));
      } catch {
        /* partial line from an interrupted run */
      }
    }
  }
  return lines;
}

const records = readRuns();
if (!records.length) {
  console.error(
    `No interaction records in ${path.relative(ROOT, INTERACTIONS_DIR)}/ — run with E2E_RECORD_INTERACTIONS=on first.`
  );
  process.exit(1);
}

// testid → { tests, paths }
const touched = new Map();
for (const r of records) {
  for (const id of r.ids) {
    const t = touched.get(id) || { tests: 0, paths: new Set() };
    t.tests++;
    for (const p of r.at?.[id] || ['']) t.paths.add(p);
    touched.set(id, t);
  }
}

const { entries, templates, files } = buildInventory();
const exact = new Map();
for (const e of entries) {
  if (e.value !== undefined) {
    if (!exact.has(e.value)) exact.set(e.value, []);
    exact.get(e.value).push(e);
  }
}
const patterned = entries.filter((e) => e.re);

/**
 * Credit every entry the id matches, except route-bound entries (files under app/) whose route
 * doesn't match any pathname the id was touched on — so a create-page touch doesn't cover the
 * edit page's copy of the same testid. Entries in components/ can't be told apart this way:
 * when one id credits several entries they're flagged `shared`.
 */
const unmatched = [];
for (const [id, t] of touched) {
  const candidates = [...(exact.get(id) || []), ...patterned.filter((e) => e.re.test(id))];
  if (!candidates.length) {
    unmatched.push(id);
    continue;
  }
  const paths = [...t.paths];
  const credited = candidates.filter((e) => !e.route || paths.some((p) => !p || e.route.test(p)));
  for (const e of credited) {
    e.hits = (e.hits || 0) + t.tests;
    if (credited.filter((c) => !c.dead).length > 1) e.shared = true;
  }
}

// ─── summary ─────────────────────────────────────────────────

const rows = new Map(); // area → screen → counts
const bump = (area, screen, key) => {
  if (!rows.has(area)) rows.set(area, new Map());
  const a = rows.get(area);
  if (!a.has(screen)) {
    a.set(screen, { total: 0, touched: 0, shared: 0, untouched: 0, dead: 0, nonInt: 0 });
  }
  a.get(screen)[key]++;
};
for (const e of entries) {
  if (e.dead) bump(e.area, e.screen, 'dead');
  else if (!e.interactive) bump(e.area, e.screen, 'nonInt');
  else {
    bump(e.area, e.screen, 'total');
    bump(e.area, e.screen, e.hits ? 'touched' : 'untouched');
    if (e.hits && e.shared) bump(e.area, e.screen, 'shared');
  }
}

const pct = (a, b) => (b ? `${Math.round((100 * a) / b)}%` : '—');
const counts = countInventory(entries);
const live = entries.filter((e) => !e.dead && e.interactive);
const liveTouched = live.filter((e) => e.hits).length;
const statuses = records.reduce((m, r) => ((m[r.status] = (m[r.status] || 0) + 1), m), {});

const md = [];
md.push('# Interaction coverage — charts · dashboards · reports');
md.push('');
md.push(
  '> Generated by `npm run e2e:interactions:report` from `test-results/interactions/*.jsonl` ' +
    '(recorded with `npm run e2e:interactions:record`). Do not edit by hand.'
);
md.push('');
md.push(
  `**${liveTouched} / ${live.length} live interactive elements touched (${pct(liveTouched, live.length)})** · ` +
    `${records.length} tests recorded (${Object.entries(statuses)
      .map(([s, n]) => `${n} ${s}`)
      .join(', ')}) · ${touched.size} distinct testids touched`
);
md.push('');
md.push(
  `Inventory: ${files.length} files · ${counts.total} entries — ${counts.interactive} interactive, ` +
    `${counts.nonInteractive} non-interactive, ${counts.dead} dead · ${counts.derived} derived from ` +
    `component usages (Combobox / DatePicker / ConfirmationDialog / forwarded props) · ` +
    `${counts.patterns} regex patterns (${counts.loose} loose) · ${templates} component templates not counted.`
);
md.push('');
md.push('## Summary');
md.push('');
md.push(
  '`Touched*` = touched only through a testid that also exists at another site (same id rendered ' +
    'by several components), so the touch may have been on the other copy.'
);
md.push('');
md.push(
  '| Area | Screen (dir) | Interactive | Touched | of which shared* | Untouched | Coverage | Dead | Non-interactive |'
);
md.push('|---|---|---:|---:|---:|---:|---:|---:|---:|');
for (const [area, screens] of [...rows].sort()) {
  const t = { total: 0, touched: 0, shared: 0, untouched: 0, dead: 0, nonInt: 0 };
  for (const [screen, c] of [...screens].sort()) {
    for (const k of Object.keys(t)) t[k] += c[k];
    md.push(
      `| ${area} | \`${screen}\` | ${c.total} | ${c.touched} | ${c.shared} | ${c.untouched} | ${pct(c.touched, c.total)} | ${c.dead} | ${c.nonInt} |`
    );
  }
  md.push(
    `| **${area}** | **all** | **${t.total}** | **${t.touched}** | **${t.shared}** | **${t.untouched}** | **${pct(t.touched, t.total)}** | **${t.dead}** | **${t.nonInt}** |`
  );
}
md.push('');

md.push('## Untouched interactive elements');
md.push('');
md.push(
  'Grouped by file. `derived` = the testid is generated by a shared component at that usage. ' +
    '`loose` = the pattern has an unresolved dynamic part, so a match is weak evidence.'
);
md.push('');
const byFile = new Map();
for (const e of live.filter((x) => !x.hits)) {
  if (!byFile.has(e.file)) byFile.set(e.file, []);
  byFile.get(e.file).push(e);
}
for (const [file, list] of [...byFile].sort()) {
  md.push(`### \`${file}\` (${list.length})`);
  md.push('');
  for (const e of list) {
    const id = e.value !== undefined ? `\`${e.value}\`` : `\`/${e.regex}/\``;
    const notes = [e.derived && `derived from ${e.derived}`, e.loose && 'loose'].filter(Boolean);
    md.push(`- :${e.line} \`<${e.tag}>\` ${id}${notes.length ? ` — ${notes.join(', ')}` : ''}`);
  }
  md.push('');
}

md.push('## Touched testids with no inventory entry');
md.push('');
md.push(
  'Outside the scanned files (nav, other features, shared ui) — or an inventory bug if they belong ' +
    'to charts / dashboards / reports.'
);
md.push('');
md.push(
  unmatched.length
    ? unmatched
        .sort()
        .map((id) => `\`${id}\``)
        .join(' · ')
    : '_none_'
);
md.push('');

writeFileSync(OUT, md.join('\n'));
console.log(
  `${liveTouched}/${live.length} live interactive touched (${pct(liveTouched, live.length)}) · ` +
    `${records.length} tests · ${unmatched.length} unmatched ids → ${path.relative(ROOT, OUT)}`
);
