# Stage 1: Dependencies (runs on native build platform - fast, no emulation)
FROM --platform=$BUILDPLATFORM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

# Stage 2: Builder (runs on native build platform - fast, no emulation)
FROM --platform=$BUILDPLATFORM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_EMBEDDED_WEBAPP_URL
ARG NEXT_PUBLIC_WEBAPP_ENVIRONMENT
ARG NEXT_PUBLIC_USAGE_DASHBOARD_ID
ARG NEXT_PUBLIC_USAGE_DASHBOARD_DOMAIN
ARG NEXT_PUBLIC_DOCS_BASE_URL
ARG NEXT_PUBLIC_AIRBYTE_URL
ARG NEXT_PUBLIC_SENTRY_DSN
ARG SENTRY_AUTH_TOKEN
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_POSTHOG_HOST
ARG NEXT_PUBLIC_POSTHOG_INGEST_HOST
ARG POSTHOG_PROXY_HOST
ARG POSTHOG_PROXY_ASSETS_HOST

ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_EMBEDDED_WEBAPP_URL=$NEXT_PUBLIC_EMBEDDED_WEBAPP_URL
ENV NEXT_PUBLIC_WEBAPP_ENVIRONMENT=$NEXT_PUBLIC_WEBAPP_ENVIRONMENT
ENV NEXT_PUBLIC_USAGE_DASHBOARD_ID=$NEXT_PUBLIC_USAGE_DASHBOARD_ID
ENV NEXT_PUBLIC_USAGE_DASHBOARD_DOMAIN=$NEXT_PUBLIC_USAGE_DASHBOARD_DOMAIN
ENV NEXT_PUBLIC_DOCS_BASE_URL=$NEXT_PUBLIC_DOCS_BASE_URL
ENV NEXT_PUBLIC_AIRBYTE_URL=$NEXT_PUBLIC_AIRBYTE_URL
ENV NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN
ENV SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
ENV NEXT_PUBLIC_POSTHOG_KEY=$NEXT_PUBLIC_POSTHOG_KEY
ENV NEXT_PUBLIC_POSTHOG_HOST=$NEXT_PUBLIC_POSTHOG_HOST
ENV NEXT_PUBLIC_POSTHOG_INGEST_HOST=$NEXT_PUBLIC_POSTHOG_INGEST_HOST
ENV POSTHOG_PROXY_HOST=$POSTHOG_PROXY_HOST
ENV POSTHOG_PROXY_ASSETS_HOST=$POSTHOG_PROXY_ASSETS_HOST

RUN npm run build

# Stage 3: Runner (this is the only stage that runs on ARM64)
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# copying only relevant files from the previous build stage.
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3001
ENV PORT=3001
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
