/** Generated once from the pre-refactor code (ChartDataConfigurationV3.handleChartTypeChange + edit page handleFormChange) — never edit to make a test pass. */
export const EXPECTED_SWITCHES: Record<
  'create' | 'edit',
  Record<string, Record<string, unknown>>
> = {
  create: {
    'bar>line': {
      chart_type: 'line',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      customizations: {
        dataLabelPosition: 'top',
        legendPosition: 'bottom',
        orientation: 'vertical',
        showDataLabels: true,
        showLegend: true,
        showTooltip: true,
        stacked: false,
        xAxisLabelRotation: '45',
        xAxisTitle: '',
        yAxisLabelRotation: 'horizontal',
        yAxisTitle: '',
      },
    },
    'bar>pie': {
      chart_type: 'pie',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      customizations: {
        dataLabelPosition: 'inside',
        legendPosition: 'bottom',
        orientation: 'vertical',
        showDataLabels: true,
        showLegend: true,
        showTooltip: true,
        stacked: false,
        xAxisLabelRotation: '45',
        xAxisTitle: '',
        yAxisLabelRotation: 'horizontal',
        yAxisTitle: '',
      },
    },
    'bar>number': {
      chart_type: 'number',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      customizations: {
        legendPosition: 'bottom',
        orientation: 'vertical',
        showDataLabels: true,
        showLegend: true,
        showTooltip: true,
        stacked: false,
        xAxisLabelRotation: '45',
        xAxisTitle: '',
        yAxisLabelRotation: 'horizontal',
        yAxisTitle: '',
      },
    },
    'bar>table': {
      chart_type: 'table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      dimensions: ['id'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {
        legendPosition: 'bottom',
        orientation: 'vertical',
        showDataLabels: true,
        showLegend: true,
        showTooltip: true,
        stacked: false,
        xAxisLabelRotation: '45',
        xAxisTitle: '',
        yAxisLabelRotation: 'horizontal',
        yAxisTitle: '',
      },
    },
    'bar>map': {
      chart_type: 'map',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      geographic_column: 'statename',
      metrics: ['SUM(students)'],
      customizations: {
        legendPosition: 'bottom',
        orientation: 'vertical',
        showDataLabels: true,
        showLegend: true,
        showTooltip: true,
        stacked: false,
        xAxisLabelRotation: '45',
        xAxisTitle: '',
        yAxisLabelRotation: 'horizontal',
        yAxisTitle: '',
      },
    },
    'bar>pivot_table': {
      chart_type: 'pivot_table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      row_dimensions: [],
      column_dimensions: [],
      customizations: {
        legendPosition: 'bottom',
        orientation: 'vertical',
        showDataLabels: true,
        showLegend: true,
        showTooltip: true,
        stacked: false,
        xAxisLabelRotation: '45',
        xAxisTitle: '',
        yAxisLabelRotation: 'horizontal',
        yAxisTitle: '',
      },
    },
    'line>bar': {
      chart_type: 'bar',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      customizations: {
        dataLabelPosition: 'top',
        legendPosition: 'bottom',
        lineStyle: 'smooth',
        showDataLabels: true,
        showDataPoints: true,
        showLegend: true,
        showTooltip: true,
        xAxisLabelRotation: 'horizontal',
        xAxisTitle: '',
        yAxisLabelRotation: 'horizontal',
        yAxisTitle: '',
      },
    },
    'line>pie': {
      chart_type: 'pie',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      customizations: {
        dataLabelPosition: 'outside',
        legendPosition: 'bottom',
        lineStyle: 'smooth',
        showDataLabels: true,
        showDataPoints: true,
        showLegend: true,
        showTooltip: true,
        xAxisLabelRotation: 'horizontal',
        xAxisTitle: '',
        yAxisLabelRotation: 'horizontal',
        yAxisTitle: '',
      },
    },
    'line>number': {
      chart_type: 'number',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      customizations: {
        legendPosition: 'bottom',
        lineStyle: 'smooth',
        showDataLabels: true,
        showDataPoints: true,
        showLegend: true,
        showTooltip: true,
        xAxisLabelRotation: 'horizontal',
        xAxisTitle: '',
        yAxisLabelRotation: 'horizontal',
        yAxisTitle: '',
      },
    },
    'line>table': {
      chart_type: 'table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      dimensions: ['id'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {
        legendPosition: 'bottom',
        lineStyle: 'smooth',
        showDataLabels: true,
        showDataPoints: true,
        showLegend: true,
        showTooltip: true,
        xAxisLabelRotation: 'horizontal',
        xAxisTitle: '',
        yAxisLabelRotation: 'horizontal',
        yAxisTitle: '',
      },
    },
    'line>map': {
      chart_type: 'map',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      geographic_column: 'statename',
      metrics: ['SUM(students)'],
      customizations: {
        legendPosition: 'bottom',
        lineStyle: 'smooth',
        showDataLabels: true,
        showDataPoints: true,
        showLegend: true,
        showTooltip: true,
        xAxisLabelRotation: 'horizontal',
        xAxisTitle: '',
        yAxisLabelRotation: 'horizontal',
        yAxisTitle: '',
      },
    },
    'line>pivot_table': {
      chart_type: 'pivot_table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      row_dimensions: [],
      column_dimensions: [],
      customizations: {
        legendPosition: 'bottom',
        lineStyle: 'smooth',
        showDataLabels: true,
        showDataPoints: true,
        showLegend: true,
        showTooltip: true,
        xAxisLabelRotation: 'horizontal',
        xAxisTitle: '',
        yAxisLabelRotation: 'horizontal',
        yAxisTitle: '',
      },
    },
    'pie>bar': {
      chart_type: 'bar',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      customizations: {
        chartStyle: 'donut',
        dataLabelPosition: 'inside',
        labelFormat: 'percentage',
        legendPosition: 'bottom',
        showDataLabels: true,
        showLegend: true,
        showTooltip: true,
      },
    },
    'pie>line': {
      chart_type: 'line',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      customizations: {
        chartStyle: 'donut',
        dataLabelPosition: 'top',
        labelFormat: 'percentage',
        legendPosition: 'bottom',
        showDataLabels: true,
        showLegend: true,
        showTooltip: true,
      },
    },
    'pie>number': {
      chart_type: 'number',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      customizations: {
        chartStyle: 'donut',
        labelFormat: 'percentage',
        legendPosition: 'bottom',
        showDataLabels: true,
        showLegend: true,
        showTooltip: true,
      },
    },
    'pie>table': {
      chart_type: 'table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      dimensions: ['id'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {
        chartStyle: 'donut',
        labelFormat: 'percentage',
        legendPosition: 'bottom',
        showDataLabels: true,
        showLegend: true,
        showTooltip: true,
      },
    },
    'pie>map': {
      chart_type: 'map',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      geographic_column: 'statename',
      metrics: ['SUM(students)'],
      customizations: {
        chartStyle: 'donut',
        labelFormat: 'percentage',
        legendPosition: 'bottom',
        showDataLabels: true,
        showLegend: true,
        showTooltip: true,
      },
    },
    'pie>pivot_table': {
      chart_type: 'pivot_table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      row_dimensions: [],
      column_dimensions: [],
      customizations: {
        chartStyle: 'donut',
        labelFormat: 'percentage',
        legendPosition: 'bottom',
        showDataLabels: true,
        showLegend: true,
        showTooltip: true,
      },
    },
    'number>bar': {
      chart_type: 'bar',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      metrics: ['SUM(students)'],
      customizations: {
        decimalPlaces: 0,
        numberFormat: 'default',
        numberPrefix: '~',
        numberSize: 'medium',
        numberSuffix: '',
        subtitle: 'Across all states',
      },
    },
    'number>line': {
      chart_type: 'line',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      metrics: ['SUM(students)'],
      customizations: {
        decimalPlaces: 0,
        numberFormat: 'default',
        numberPrefix: '~',
        numberSize: 'medium',
        numberSuffix: '',
        subtitle: 'Across all states',
      },
    },
    'number>pie': {
      chart_type: 'pie',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      metrics: ['SUM(students)'],
      customizations: {
        decimalPlaces: 0,
        numberFormat: 'default',
        numberPrefix: '~',
        numberSize: 'medium',
        numberSuffix: '',
        subtitle: 'Across all states',
      },
    },
    'number>table': {
      chart_type: 'table',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      metrics: ['SUM(students)'],
      dimensions: ['id'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {
        decimalPlaces: 0,
        numberFormat: 'default',
        numberPrefix: '~',
        numberSize: 'medium',
        numberSuffix: '',
        subtitle: 'Across all states',
      },
    },
    'number>map': {
      chart_type: 'map',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      metrics: ['SUM(students)'],
      customizations: {
        decimalPlaces: 0,
        numberFormat: 'default',
        numberPrefix: '~',
        numberSize: 'medium',
        numberSuffix: '',
        subtitle: 'Across all states',
      },
    },
    'number>pivot_table': {
      chart_type: 'pivot_table',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      metrics: ['SUM(students)'],
      row_dimensions: [],
      column_dimensions: [],
      customizations: {
        decimalPlaces: 0,
        numberFormat: 'default',
        numberPrefix: '~',
        numberSize: 'medium',
        numberSuffix: '',
        subtitle: 'Across all states',
      },
    },
    'table>bar': {
      chart_type: 'bar',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      dimensions: ['statename', 'districtname'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {},
    },
    'table>line': {
      chart_type: 'line',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      dimensions: ['statename', 'districtname'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {},
    },
    'table>pie': {
      chart_type: 'pie',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      dimensions: ['statename', 'districtname'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {},
    },
    'table>number': {
      chart_type: 'number',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      dimensions: ['statename', 'districtname'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {},
    },
    'table>map': {
      chart_type: 'map',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      geographic_column: 'statename',
      metrics: ['SUM(students)'],
      dimensions: ['statename', 'districtname'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {},
    },
    'table>pivot_table': {
      chart_type: 'pivot_table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      dimensions: ['statename', 'districtname'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      row_dimensions: [],
      column_dimensions: [],
      customizations: {},
    },
    'map>bar': {
      chart_type: 'bar',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      value_column: 'students',
      metrics: ['SUM(students)'],
      customizations: {
        colorScheme: 'Greens',
        nullValueLabel: 'No Data',
        showLegend: true,
        showTooltip: true,
        title: '',
      },
    },
    'map>line': {
      chart_type: 'line',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      value_column: 'students',
      metrics: ['SUM(students)'],
      customizations: {
        colorScheme: 'Greens',
        nullValueLabel: 'No Data',
        showLegend: true,
        showTooltip: true,
        title: '',
      },
    },
    'map>pie': {
      chart_type: 'pie',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      value_column: 'students',
      metrics: ['SUM(students)'],
      customizations: {
        colorScheme: 'Greens',
        nullValueLabel: 'No Data',
        showLegend: true,
        showTooltip: true,
        title: '',
      },
    },
    'map>number': {
      chart_type: 'number',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      value_column: 'students',
      metrics: ['SUM(students)'],
      customizations: {
        colorScheme: 'Greens',
        nullValueLabel: 'No Data',
        showLegend: true,
        showTooltip: true,
        title: '',
      },
    },
    'map>table': {
      chart_type: 'table',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      value_column: 'students',
      metrics: ['SUM(students)'],
      customizations: {
        colorScheme: 'Greens',
        nullValueLabel: 'No Data',
        showLegend: true,
        showTooltip: true,
        title: '',
      },
    },
    'map>pivot_table': {
      chart_type: 'pivot_table',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      value_column: 'students',
      metrics: ['SUM(students)'],
      customizations: {
        colorScheme: 'Greens',
        nullValueLabel: 'No Data',
        showLegend: true,
        showTooltip: true,
        title: '',
      },
    },
    'pivot_table>bar': {
      chart_type: 'bar',
      computation_type: 'aggregated',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      row_dimensions: ['statename', 'districtname'],
      column_dimensions: ['climate_event'],
      customizations: { decimalPlaces: 0, numberFormat: 'default' },
    },
    'pivot_table>line': {
      chart_type: 'line',
      computation_type: 'aggregated',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      row_dimensions: ['statename', 'districtname'],
      column_dimensions: ['climate_event'],
      customizations: { decimalPlaces: 0, numberFormat: 'default' },
    },
    'pivot_table>pie': {
      chart_type: 'pie',
      computation_type: 'aggregated',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      row_dimensions: ['statename', 'districtname'],
      column_dimensions: ['climate_event'],
      customizations: { decimalPlaces: 0, numberFormat: 'default' },
    },
    'pivot_table>number': {
      chart_type: 'number',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      row_dimensions: ['statename', 'districtname'],
      column_dimensions: ['climate_event'],
      customizations: { decimalPlaces: 0, numberFormat: 'default' },
    },
    'pivot_table>table': {
      chart_type: 'table',
      computation_type: 'aggregated',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      dimensions: ['id'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      row_dimensions: ['statename', 'districtname'],
      column_dimensions: ['climate_event'],
      customizations: { decimalPlaces: 0, numberFormat: 'default' },
    },
    'pivot_table>map': {
      chart_type: 'map',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      geographic_column: 'statename',
      metrics: ['SUM(students)'],
      row_dimensions: ['statename', 'districtname'],
      column_dimensions: ['climate_event'],
      customizations: { decimalPlaces: 0, numberFormat: 'default' },
    },
  },
  edit: {
    'bar>line': {
      chart_type: 'line',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      table_columns: [],
      customizations: {
        lineStyle: 'smooth',
        showDataPoints: true,
        showTooltip: true,
        showLegend: true,
        showDataLabels: true,
        dataLabelPosition: 'inside',
        xAxisTitle: '',
        yAxisTitle: '',
        xAxisLabelRotation: 'horizontal',
        yAxisLabelRotation: 'horizontal',
        legendDisplay: 'paginated',
        legendPosition: 'top',
      },
    },
    'bar>pie': {
      chart_type: 'pie',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        chartStyle: 'donut',
        labelFormat: 'percentage',
        showDataLabels: true,
        dataLabelPosition: 'inside',
        showTooltip: true,
        showLegend: true,
        legendPosition: 'top',
        legendDisplay: 'paginated',
      },
    },
    'bar>number': {
      chart_type: 'number',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        numberSize: 'medium',
        subtitle: '',
        numberFormat: 'default',
        decimalPlaces: 0,
        numberPrefix: '',
        numberSuffix: '',
      },
    },
    'bar>table': {
      chart_type: 'table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      x_axis_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      dimensions: ['id'],
      table_columns: ['statename', 'students', 'male_score'],
      customizations: {},
    },
    'bar>map': {
      chart_type: 'map',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      geographic_column: 'statename',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      table_columns: [],
      customizations: {
        colorScheme: 'Blues',
        showTooltip: true,
        showLegend: true,
        nullValueLabel: 'No Data',
        title: '',
        showLabels: false,
      },
    },
    'bar>pivot_table': {
      chart_type: 'pivot_table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      table_columns: [],
      row_dimensions: [],
      column_dimensions: [],
      customizations: { numberFormat: 'default', decimalPlaces: 0 },
    },
    'line>bar': {
      chart_type: 'bar',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      table_columns: [],
      customizations: {
        orientation: 'vertical',
        showDataLabels: true,
        dataLabelPosition: 'bottom',
        stacked: false,
        showTooltip: true,
        showLegend: true,
        xAxisTitle: '',
        yAxisTitle: '',
        xAxisLabelRotation: '45',
        yAxisLabelRotation: 'horizontal',
        legendDisplay: 'paginated',
        legendPosition: 'top',
      },
    },
    'line>pie': {
      chart_type: 'pie',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        chartStyle: 'donut',
        labelFormat: 'percentage',
        showDataLabels: true,
        dataLabelPosition: 'bottom',
        showTooltip: true,
        showLegend: true,
        legendPosition: 'top',
        legendDisplay: 'paginated',
      },
    },
    'line>number': {
      chart_type: 'number',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        numberSize: 'medium',
        subtitle: '',
        numberFormat: 'default',
        decimalPlaces: 0,
        numberPrefix: '',
        numberSuffix: '',
      },
    },
    'line>table': {
      chart_type: 'table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      x_axis_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      dimensions: ['id'],
      table_columns: ['statename', 'students', 'male_score'],
      customizations: {},
    },
    'line>map': {
      chart_type: 'map',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      geographic_column: 'statename',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      table_columns: [],
      customizations: {
        colorScheme: 'Blues',
        showTooltip: true,
        showLegend: true,
        nullValueLabel: 'No Data',
        title: '',
        showLabels: false,
      },
    },
    'line>pivot_table': {
      chart_type: 'pivot_table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      table_columns: [],
      row_dimensions: [],
      column_dimensions: [],
      customizations: { numberFormat: 'default', decimalPlaces: 0 },
    },
    'pie>bar': {
      chart_type: 'bar',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        orientation: 'vertical',
        showDataLabels: true,
        dataLabelPosition: 'inside',
        stacked: false,
        showTooltip: true,
        showLegend: true,
        xAxisTitle: '',
        yAxisTitle: '',
        xAxisLabelRotation: '45',
        yAxisLabelRotation: 'horizontal',
        legendDisplay: 'paginated',
        legendPosition: 'top',
      },
    },
    'pie>line': {
      chart_type: 'line',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        lineStyle: 'smooth',
        showDataPoints: true,
        showTooltip: true,
        showLegend: true,
        showDataLabels: true,
        dataLabelPosition: 'inside',
        xAxisTitle: '',
        yAxisTitle: '',
        xAxisLabelRotation: 'horizontal',
        yAxisLabelRotation: 'horizontal',
        legendDisplay: 'paginated',
        legendPosition: 'top',
      },
    },
    'pie>number': {
      chart_type: 'number',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        numberSize: 'medium',
        subtitle: '',
        numberFormat: 'default',
        decimalPlaces: 0,
        numberPrefix: '',
        numberSuffix: '',
      },
    },
    'pie>table': {
      chart_type: 'table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      x_axis_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      dimensions: ['id'],
      table_columns: ['statename', 'students'],
      customizations: {},
    },
    'pie>map': {
      chart_type: 'map',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      geographic_column: 'statename',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        colorScheme: 'Blues',
        showTooltip: true,
        showLegend: true,
        nullValueLabel: 'No Data',
        title: '',
        showLabels: false,
      },
    },
    'pie>pivot_table': {
      chart_type: 'pivot_table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      extra_dimension_column: 'climate_event',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      table_columns: [],
      row_dimensions: [],
      column_dimensions: [],
      customizations: { numberFormat: 'default', decimalPlaces: 0 },
    },
    'number>bar': {
      chart_type: 'bar',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        orientation: 'vertical',
        showDataLabels: false,
        dataLabelPosition: 'top',
        stacked: false,
        showTooltip: true,
        showLegend: true,
        xAxisTitle: '',
        yAxisTitle: '',
        xAxisLabelRotation: '45',
        yAxisLabelRotation: 'horizontal',
        legendDisplay: 'paginated',
        legendPosition: 'top',
        subtitle: 'Across all states',
      },
    },
    'number>line': {
      chart_type: 'line',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        lineStyle: 'smooth',
        showDataPoints: true,
        showTooltip: true,
        showLegend: true,
        showDataLabels: false,
        dataLabelPosition: 'top',
        xAxisTitle: '',
        yAxisTitle: '',
        xAxisLabelRotation: 'horizontal',
        yAxisLabelRotation: 'horizontal',
        legendDisplay: 'paginated',
        legendPosition: 'top',
        subtitle: 'Across all states',
      },
    },
    'number>pie': {
      chart_type: 'pie',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        chartStyle: 'donut',
        labelFormat: 'percentage',
        showDataLabels: true,
        dataLabelPosition: 'outside',
        showTooltip: true,
        showLegend: true,
        legendPosition: 'top',
        legendDisplay: 'paginated',
        subtitle: 'Across all states',
      },
    },
    'number>table': {
      chart_type: 'table',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      metrics: ['SUM(students)'],
      dimensions: ['id'],
      table_columns: ['students'],
      customizations: { subtitle: 'Across all states' },
    },
    'number>map': {
      chart_type: 'map',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      value_column: 'students',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        colorScheme: 'Blues',
        showTooltip: true,
        showLegend: true,
        nullValueLabel: 'No Data',
        title: '',
        showLabels: false,
        subtitle: 'Across all states',
      },
    },
    'number>pivot_table': {
      chart_type: 'pivot_table',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      metrics: ['SUM(students)'],
      table_columns: [],
      row_dimensions: [],
      column_dimensions: [],
      customizations: { numberFormat: 'default', decimalPlaces: 0, subtitle: 'Across all states' },
    },
    'table>bar': {
      chart_type: 'bar',
      computation_type: 'aggregated',
      dimension_column: 'id',
      aggregate_column: 'country',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      dimensions: ['statename', 'districtname'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {
        orientation: 'vertical',
        showDataLabels: false,
        dataLabelPosition: 'top',
        stacked: false,
        showTooltip: true,
        showLegend: true,
        xAxisTitle: '',
        yAxisTitle: '',
        xAxisLabelRotation: '45',
        yAxisLabelRotation: 'horizontal',
        legendDisplay: 'paginated',
        legendPosition: 'top',
      },
    },
    'table>line': {
      chart_type: 'line',
      computation_type: 'aggregated',
      dimension_column: 'id',
      aggregate_column: 'country',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      dimensions: ['statename', 'districtname'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {
        lineStyle: 'smooth',
        showDataPoints: true,
        showTooltip: true,
        showLegend: true,
        showDataLabels: false,
        dataLabelPosition: 'top',
        xAxisTitle: '',
        yAxisTitle: '',
        xAxisLabelRotation: 'horizontal',
        yAxisLabelRotation: 'horizontal',
        legendDisplay: 'paginated',
        legendPosition: 'top',
      },
    },
    'table>pie': {
      chart_type: 'pie',
      computation_type: 'aggregated',
      dimension_column: 'id',
      aggregate_column: 'country',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      dimensions: ['statename', 'districtname'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {
        chartStyle: 'donut',
        labelFormat: 'percentage',
        showDataLabels: true,
        dataLabelPosition: 'outside',
        showTooltip: true,
        showLegend: true,
        legendPosition: 'top',
        legendDisplay: 'paginated',
      },
    },
    'table>number': {
      chart_type: 'number',
      computation_type: 'aggregated',
      dimension_column: 'id',
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_column: 'country',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      dimensions: ['statename', 'districtname'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {
        numberSize: 'medium',
        subtitle: '',
        numberFormat: 'default',
        decimalPlaces: 0,
        numberPrefix: '',
        numberSuffix: '',
      },
    },
    'table>map': {
      chart_type: 'map',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      geographic_column: 'id',
      value_column: 'country',
      metrics: ['SUM(students)'],
      dimensions: ['statename', 'districtname'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      customizations: {
        colorScheme: 'Blues',
        showTooltip: true,
        showLegend: true,
        nullValueLabel: 'No Data',
        title: '',
        showLabels: false,
      },
    },
    'table>pivot_table': {
      chart_type: 'pivot_table',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      dimensions: ['statename', 'districtname'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      row_dimensions: [],
      column_dimensions: [],
      customizations: { numberFormat: 'default', decimalPlaces: 0 },
    },
    'map>bar': {
      chart_type: 'bar',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      value_column: 'students',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        orientation: 'vertical',
        showDataLabels: false,
        dataLabelPosition: 'top',
        stacked: false,
        showTooltip: true,
        showLegend: true,
        xAxisTitle: '',
        yAxisTitle: '',
        xAxisLabelRotation: '45',
        yAxisLabelRotation: 'horizontal',
        legendDisplay: 'paginated',
        legendPosition: 'top',
      },
    },
    'map>line': {
      chart_type: 'line',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      value_column: 'students',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        lineStyle: 'smooth',
        showDataPoints: true,
        showTooltip: true,
        showLegend: true,
        showDataLabels: false,
        dataLabelPosition: 'top',
        xAxisTitle: '',
        yAxisTitle: '',
        xAxisLabelRotation: 'horizontal',
        yAxisLabelRotation: 'horizontal',
        legendDisplay: 'paginated',
        legendPosition: 'top',
      },
    },
    'map>pie': {
      chart_type: 'pie',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      value_column: 'students',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        chartStyle: 'donut',
        labelFormat: 'percentage',
        showDataLabels: true,
        dataLabelPosition: 'outside',
        showTooltip: true,
        showLegend: true,
        legendPosition: 'top',
        legendDisplay: 'paginated',
      },
    },
    'map>number': {
      chart_type: 'number',
      computation_type: 'aggregated',
      dimension_column: 'statename',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      value_column: 'students',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: {
        numberSize: 'medium',
        subtitle: '',
        numberFormat: 'default',
        decimalPlaces: 0,
        numberPrefix: '',
        numberSuffix: '',
      },
    },
    'map>table': {
      chart_type: 'table',
      computation_type: 'aggregated',
      x_axis_column: 'statename',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      value_column: 'students',
      metrics: ['SUM(students)'],
      table_columns: ['statename', 'students'],
      customizations: {},
    },
    'map>pivot_table': {
      chart_type: 'pivot_table',
      computation_type: 'aggregated',
      aggregate_column: 'students',
      aggregate_function: 'sum',
      geographic_column: 'statename',
      value_column: 'students',
      metrics: ['SUM(students)'],
      table_columns: [],
      customizations: { numberFormat: 'default', decimalPlaces: 0 },
    },
    'pivot_table>bar': {
      chart_type: 'bar',
      computation_type: 'aggregated',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      table_columns: [],
      row_dimensions: ['statename', 'districtname'],
      column_dimensions: ['climate_event'],
      customizations: {
        orientation: 'vertical',
        showDataLabels: false,
        dataLabelPosition: 'top',
        stacked: false,
        showTooltip: true,
        showLegend: true,
        xAxisTitle: '',
        yAxisTitle: '',
        xAxisLabelRotation: '45',
        yAxisLabelRotation: 'horizontal',
        legendDisplay: 'paginated',
        legendPosition: 'top',
      },
    },
    'pivot_table>line': {
      chart_type: 'line',
      computation_type: 'aggregated',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      table_columns: [],
      row_dimensions: ['statename', 'districtname'],
      column_dimensions: ['climate_event'],
      customizations: {
        lineStyle: 'smooth',
        showDataPoints: true,
        showTooltip: true,
        showLegend: true,
        showDataLabels: false,
        dataLabelPosition: 'top',
        xAxisTitle: '',
        yAxisTitle: '',
        xAxisLabelRotation: 'horizontal',
        yAxisLabelRotation: 'horizontal',
        legendDisplay: 'paginated',
        legendPosition: 'top',
      },
    },
    'pivot_table>pie': {
      chart_type: 'pie',
      computation_type: 'aggregated',
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      table_columns: [],
      row_dimensions: ['statename', 'districtname'],
      column_dimensions: ['climate_event'],
      customizations: {
        chartStyle: 'donut',
        labelFormat: 'percentage',
        showDataLabels: true,
        dataLabelPosition: 'outside',
        showTooltip: true,
        showLegend: true,
        legendPosition: 'top',
        legendDisplay: 'paginated',
      },
    },
    'pivot_table>number': {
      chart_type: 'number',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      metrics: ['SUM(students)'],
      table_columns: [],
      row_dimensions: ['statename', 'districtname'],
      column_dimensions: ['climate_event'],
      customizations: {
        numberSize: 'medium',
        subtitle: '',
        numberFormat: 'default',
        decimalPlaces: 0,
        numberPrefix: '',
        numberSuffix: '',
      },
    },
    'pivot_table>table': {
      chart_type: 'table',
      computation_type: 'aggregated',
      aggregate_function: 'count',
      metrics: ['SUM(students)', 'AVG(male_score)'],
      dimensions: ['id'],
      table_columns: ['id', 'country', 'statename', 'districtname', 'districtcode', 'date'],
      row_dimensions: ['statename', 'districtname'],
      column_dimensions: ['climate_event'],
      customizations: {},
    },
    'pivot_table>map': {
      chart_type: 'map',
      computation_type: 'aggregated',
      dimension_column: null,
      x_axis_column: null,
      extra_dimension_column: null,
      aggregate_function: 'count',
      geographic_column: 'statename',
      metrics: ['SUM(students)'],
      table_columns: [],
      row_dimensions: ['statename', 'districtname'],
      column_dimensions: ['climate_event'],
      customizations: {
        colorScheme: 'Blues',
        showTooltip: true,
        showLegend: true,
        nullValueLabel: 'No Data',
        title: '',
        showLabels: false,
      },
    },
  },
};
