name: Build and Deploy

on:
  push:
    branches: 
      - main
      - staging
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app_environment:
        description: 'App environment (NEXT_PUBLIC_WEBAPP_ENVIRONMENT)'
        required: false
        default: 'staging'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      # Set app environment
      - name: Set app environment
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.app_environment }}" != "" ]]; then
            echo "APP_ENVIRONMENT=${{ github.event.inputs.app_environment }}" >> $GITHUB_ENV
          else
            echo "APP_ENVIRONMENT=staging" >> $GITHUB_ENV
          fi
      
      # Build on GitHub Actions
      - name: Install and Build
        run: |
          npm ci
          npm run build
        env:
          NEXT_PUBLIC_BACKEND_URL: ${{ secrets.STAGING_BACKEND_URL }}
          NEXT_PUBLIC_EMBEDDED_WEBAPP_URL: ${{ secrets.STAGING_EMBEDDED_WEBAPP_URL }}
          NEXT_PUBLIC_WEBAPP_ENVIRONMENT: ${{ env.APP_ENVIRONMENT }}
      
      # Package the pre-built app
      - name: Package build
        run: |
          mkdir deploy
          cp -r .next/standalone/* deploy/
          cp -r .next/static deploy/.next/
          cp -r public deploy/ || echo "No public directory"
          tar -czf build.tar.gz -C deploy .
      
      # Deploy to staging
      - name: Deploy to staging
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
          chmod 600 deploy_key
          
          scp -o StrictHostKeyChecking=no -i deploy_key \
            build.tar.gz \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/
          
          ssh -o StrictHostKeyChecking=no -i deploy_key \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/ddp/webapp_v2
            tar -xzf /tmp/build.tar.gz
            pm2 restart ddp-webapp_v2
            rm /tmp/build.tar.gz
          EOF